### ISSUE TITLE
How to generate the file?

### ISSUE THREAD

**Issue by Aapoorva** [coldmanck/VidHOI#1]
I am working on HOI detection in Videos. Thank you for the VIDHOI dataset and new Spatial-Temporal baseline.
Can you clarify how can I generate **val_instances_predictions_train_small_vidor_with_pseudo_labels.pth** file?

**Comment by coldmanck** [comment]
Hi @Aapoorva Thank you for your interest in our work!

Sorry that I didn't manage to include that file. I have uploaded the file and you can download it from [here](https://drive.google.com/drive/folders/1ONaZFOF5Kj0mxQZjl2F83vQxaz6jAQHE?usp=sharing).

Note that `val_instances_predictions_train_small_vidor_with_pseudo_labels.pth` is for "removing incompatible testing frames with ground truth boxes that no any bounding box/human poses got predicted by the trajectory generation/human pose prediction model". For fair comparisons, we only evaluate on the final 21,758 frames. This is done by replacing the default value of `VIDOR.TEST_PREDICT_BOX_LISTS` from `val_frame_annots.json` to `val_instances_predictions_train_small_vidor_with_pseudo_labels.pth`.

**Comment by Aapoorva** [comment]
Hi @coldmanck Thanks this will help.
Can you also clarify which frames should be there in frames lists train.csv and val.csv files as the acc. to paper, there are 7.3M frames in VIDHOI but frames generated from the script given slowfast/datasets/vidor-github/extract_vidor_frames.sh gives ~7.6M frames?

**Comment by coldmanck** [comment]
[This line](https://github.com/coldmanck/VidHOI/blob/b0b52b9b7364ff27b29b72da5b1de661d0fe56d2/slowfast/datasets/vidor_dataset.py#L139) prints the number of frames actually used for training/validation, respectively.

Training stats: 6,505,157 frames
![1](https://user-images.githubusercontent.com/7726203/123398461-26774380-d5d6-11eb-8da7-86abae1f1d2d.png)

Validation stats: 769,425 frames
![3](https://user-images.githubusercontent.com/7726203/123401898-cb475000-d5d9-11eb-8fd1-7b565e20d31b.png)

6,505,157 + 769,425 = 7,274,582 ~ 7.3M frames
