### ISSUE TITLE
Download Checkpoints

### ISSUE THREAD

**Issue by jhj7905** [coldmanck/VidHOI#13]
Hello, @coldmanck 
Thank you for providing your work.
I confirmed that the checkpoint file is now unavailable...
Do you have a plan to provide checkpoint again?

**Comment by coldmanck** [comment]
Hi @jhj7905 thanks for your interest in our work! Unfortunately, as stated in the readme.md, the checkpoint has been deleted due to lack of the cloud space. Please try to train one yourself following the instructions.
