### ISSUE TITLE
cad-120 dateset

### ISSUE THREAD

**Issue by mytk2012** [coldmanck/VidHOI#2]
Aprreciate for your nice work! Can you share me with CAD-120 dataset? It seemed that there are some incomplete CAD-120 dataset on the Internet. And paper(LIGHTEN-Learning-Interactions-with-Graphs-and-Hierarchical-TEmporal-Networks-for-HOI) used the features that it has encoded. Does CAD-120 dataset keep secret?

**Comment by coldmanck** [comment]
Hi @mytk2012 Our work doesn't involve experiments on CAD-120 dataset. Please refer to [this link](https://github.com/praneeth11009/LIGHTEN-Learning-Interactions-with-Graphs-and-Hierarchical-TEmporal-Networks-for-HOI/issues/1) for some help.

Edit: I see that you're coming from there. I do not have the dataset either, sorry about that!

**Comment by mytk2012** [comment]
Yeah, but still appreciate for your work due to your novel dataset, it give me another choice instead of only CAD-120 dataset. Hope your dataset and model can be widespread soon.
