### ISSUE TITLE
Parts of the download link were invalid, could you please fix it or provide a new one

### ISSUE THREAD

**Issue by zml-ai** [coldmanck/VidHOI#4]
Thanks for your good work, 
I find parts of the download link were invalid, could you please fix it or provide a new one?
error in training videos (part 4) [[Baidu]](https://pan.baidu.com/s/1Xjqx7HNR1R__8OyOO8Aayg?pwd=2u2n) [MD5: a8dd511d36da4057a9b52f461065126f]

**Comment by xdshang** [comment]
> Thanks for your good work, I find parts of the download link were invalid, could you please fix it or provide a new one? error in training videos (part 4) [[Baidu]](https://pan.baidu.com/s/1Xjqx7HNR1R__8OyOO8Aayg?pwd=2u2n) [MD5: a8dd511d36da4057a9b52f461065126f]

Can I have the username of your Baidu account? I might need to share the file with you privately as the public link is blocked.

**Comment by zml-ai** [comment]
> 



> > Thanks for your good work, I find parts of the download link were invalid, could you please fix it or provide a new one? error in training videos (part 4) [[Baidu]](https://pan.baidu.com/s/1Xjqx7HNR1R__8OyOO8Aayg?pwd=2u2n) [MD5: a8dd511d36da4057a9b52f461065126f]
> 
> Can I have the username of your Baidu account? I might need to share the file with you privately as the public link is blocked.

**Comment by zml-ai** [comment]
> > Thanks for your good work, I find parts of the download link were invalid, could you please fix it or provide a new one? error in training videos (part 4) [[Baidu]](https://pan.baidu.com/s/1Xjqx7HNR1R__8OyOO8Aayg?pwd=2u2n) [MD5: a8dd511d36da4057a9b52f461065126f]
> 
> Can I have the username of your Baidu account? I might need to share the file with you privately as the public link is blocked.

I really appreciate it. 
'_Wakingup' is my Baidu account. If this doesn't work, please send my e-mail: lizm@hust.edu.cn.

Also please provide the link for validation videos  [[Baidu]](https://pan.baidu.com/s/1wbc_MEJpXkeMFMhNV_MVDw?pwd=9qyu) [MD5: b5386d83faeed98b8342ed31be737900]
This link on the official web matches the error file.
Thanks again.
