### ISSUE TITLE
train.csv/val.csv are not found

### ISSUE THREAD

**Issue by mstone1123** [coldmanck/VidHOI#6]
Thank you for great work!
I encountered an error due to missing train.csv/val.csv of frame lists. 
Could you please clarify how can I get these file, or upload them?

Error log:
` File "/home/VidHOI/slowfast/datasets/vidor_helper.py", line 41, in load_image_lists
    with PathManager.open(list_filename, "r") as f:
  File "/opt/conda/envs/vidhoi/lib/python3.6/site-packages/fvcore/common/file_io.py", line 587, in open
    path, mode, buffering=buffering, **kwargs
  File "/opt/conda/envs/vidhoi/lib/python3.6/site-packages/fvcore/common/file_io.py", line 381, in _open
    opener=opener,
FileNotFoundError: [Errno 2] No such file or directory: '/home/VidHOI/slowfast/datasets/vidor-github/frame_lists/val.csv'`

**Comment by coldmanck** [comment]
@mstone1123 Please refer to the files under the `frame_lists/` folder [here](https://drive.google.com/drive/folders/1PGZ-5vGXphL5dgUWrlePZn5lQ2ejq62K?usp=sharing).

**Comment by mstone1123** [comment]
@coldmanck Thank you for your handling!
