### ISSUE TITLE
Missing parameters 'orig_video_idx' in the output json

### ISSUE THREAD

**Issue by xiaoxiaoczw** [coldmanck/VidHOI#7]
hi,

thank you for your excellent work! 
When I ran ```vidor_eval.ipynb```, I found that ```'orig_video_idx' ```parameter was missing in the [output](https://drive.google.com/drive/folders/1ONaZFOF5Kj0mxQZjl2F83vQxaz6jAQHE) json file you provided. Did I ignore the correct file? 
Thanks!

**Comment by coldmanck** [comment]
Hi @xiaoxiaoczw Thank you for your interest in our work! 

I doubt the missing `orig_video_idx` variable would have any impact on running `vidor_eval.ipynb`.  Please comment out the code lines including `is_demo` and try again. Do let me know if you find anything weird then :)

**Comment by xiaoxiaoczw** [comment]
Hi,

But in addition to ```is_demo```, ```orig_video_idx```parameter still needs to be used to locate img-path.
``` python
img_path = 'slowfast/datasets/vidor/frames/' + res[idx]['orig_video_idx'][0] + '.jpg'
```

**Comment by jhj7905** [comment]
@xiaoxiaoczw 
I confirmed the vidor_eval.ipynb and test_net_vidor.py.
Finally I knew that you should run the test_net_vidor.py with cfg.DEMO.ENABLE_ALL True.
Then you can get the json file including orig_video_idx key.
